
- name: "Creates digitalocean droplet and space, performs initial setup, adds relevant playbooks to users account."
  hosts: testing_servers
  gather_facts: false

  roles:
    - spawn-server
    - setup-server
    - print-dns-setup

