
- name: "Creates Digitalocean droplet or Proxmox kvm, performs initial setup of server."
  hosts: testing_servers
  gather_facts: false

  roles:
    - spawn-server
    - setup-server
    - print-dns-setup
    - config-changes