---

- name: Immediately shutdown the VM
  community.general.shutdown:
    delay: 0
  ignore_unreachable: true
  ignore_errors: true

- name: Stop the proxmox VM
  delegate_to: 127.0.0.1
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    name: "{{ server_url }}"
    node: "{{ proxmox_node }}"
    force: true
    state: stopped
    timeout: 180
  register: old_server_info

- debug:
    msg: "{{ old_server_info }}"

- name: Set string fact for VM stopped status
  set_fact:
    stopped_status: "status: stopped"

- name: Check if target VM is stopped for up to 180 seconds
  delegate_to: "{{ proxmox_node }}"
  command: sudo qm status {{ vmid }}
  register: vm_status
  until: vm_status.stdout == stopped_status
  retries: 12
  delay: 15

- name: Delete the proxmox VM
  delegate_to: 127.0.0.1
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    name: "{{ server_url }}"
    node: "{{ proxmox_node }}"
    force: true
    state: absent
    timeout: 180
  register: old_server_info_2

- debug:
    msg: "{{ old_server_info_2 }}"