       
- name: Remove existing Digital Ocean Droplet
  delegate_to: 127.0.0.1
  community.digitalocean.digital_ocean_droplet: 
    state: absent
    name: '{{ server_url }}'
    oauth_token: '{{ do_api_token }}'
    region: '{{ do_droplet_region }}'
    image: '{{ do_image }}'
    wait: yes
    unique_name: yes
  register: deleted_server_info
  when: spawn_on_digitalocean | bool

- debug:
    msg: "{{ deleted_server_info }}"
  when: spawn_on_digitalocean | bool

- name: Remove host entry to ~/.hosts file
  delegate_to: 127.0.0.1
  lineinfile:
    path: '~/.hosts'
    create: true
    regexp: "^.*{{ server_url }}$"
    mode: '0600'
    state: absent
