---

- name: Delete A records that point to the servers IP
  delegate_to: 127.0.0.1
  community.general.cloudflare_dns:
    zone: '{{ cloudflare_zone_name }}'
    record: '{{ item }}'
    type: A
    account_email: '{{ cloudflare_email }}'
    account_api_token: '{{ cloudflare_api_token }}'
    state: absent
  with_items: "{{ server_subdomains }}"
  register: record_ipv4

- name: Print the deletion status.
  delegate_to: 127.0.0.1
  ansible.builtin.debug:
    msg: Record IPv4 - {{ record_ipv4 }}

- name: Delete AAAA records that point to the servers IP
  delegate_to: 127.0.0.1
  community.general.cloudflare_dns:
    zone: '{{ cloudflare_zone_name }}'
    record: '{{ item }}'
    type: AAAA
    account_email: '{{ cloudflare_email }}'
    account_api_token: '{{ cloudflare_api_token }}'
    state: absent
  with_items: "{{ server_subdomains }}"
  register: record_ipv6

- name: Print the deletion status.
  delegate_to: 127.0.0.1
  ansible.builtin.debug:
    msg: Record IPv6 - {{ record_ipv6 }}
