---

- name: Stop the proxmox VM
  delegate_to: 127.0.0.1
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    name: "{{ server_url }}"
    node: "{{ proxmox_node }}"
    force: true
    state: stopped
    timeout: 180
  register: old_server_info

- debug:
    msg: "{{ old_server_info }}"

- name: Pause for 15 seconds to let QEMU gather itself
  ansible.builtin.pause:
    seconds: 15

- name: Delete the proxmox VM
  delegate_to: 127.0.0.1
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    name: "{{ server_url }}"
    node: "{{ proxmox_node }}"
    state: absent
    timeout: 180
  register: old_server_info_2

- debug:
    msg: "{{ old_server_info_2 }}"