
# Delete DigitalOcean Server:
- import_tasks: "{{ role_path }}/tasks/delete_server.yml"
  tags: always

# Delete CloudFlare DNS Record:
- import_tasks: "{{ role_path }}/tasks/delete_cloudflare_dns.yml"
  tags: [ 'never', 'cloudflare-dns' ]