---

# Delete DigitalOcean Server:
- import_tasks: "{{ role_path }}/tasks/delete_do_droplet.yml"
  when: spawn_on_digitalocean | bool

# Delete Proxmox VM:
- import_tasks: "{{ role_path }}/tasks/delete_proxmox_vm.yml"
  when: spawn_on_proxmox | bool

# Delete CloudFlare DNS Record:
- import_tasks: "{{ role_path }}/tasks/delete_cloudflare_dns.yml"
  tags: [ 'cloudflare-dns' ]
