---

# Append to server_vars.yml variable file (updatable)

- name: Add do_droplet_id line to inventory file
  delegate_to: 127.0.0.1
  lineinfile:
    path: '{{ inventory_dir }}/host_vars/{{ server_url }}/vars.yml'
    regexp: "^{{ item.key }}:.*$"
    line: "{{ item.key }}: {{ item.value }}"
    mode: '0600'
    state: present
  with_dict:
    'do_droplet_id': '{{ new_server_info.data.droplet.id }}'
  when: do_droplet_id is defined

- name: Wait for 10 seconds so host can come up
  pause:
    seconds: 10

- name: Remove host entry from known_hosts file (1/3)
  delegate_to: localhost
  known_hosts:
    name: '{{ server_url }}'
    state: absent

- name: Remove host entry from known_hosts file (2/3)
  delegate_to: localhost
  known_hosts:
    name: '{{ server_ipv4 }}'
    state: absent

- name: Remove host entry from known_hosts file if static IP is being used (3/3)
  delegate_to: localhost
  known_hosts:
    name: '{{ server_ipv4_final }}'
    state: absent
  when: set_static_ip | bool

- name: Add the server URL to known hosts
  delegate_to: localhost
  known_hosts:
    name: '{{ server_url }}'
    key: "{{ inventory_hostname }} {{ proxmox_template_host_key }}"
    state: present

- name: Add the initial server IPv4 to known hosts
  delegate_to: localhost
  known_hosts:
    name: '{{ server_ipv4 }}'
    key: "{{ server_ipv4 }} {{ proxmox_template_host_key }}"
    state: present

- name: Add the "Final server IPv4" to known hosts if static IP is being used
  delegate_to: localhost
  known_hosts:
    name: '{{ server_ipv4_final }}'
    key: "{{ server_ipv4_final }} {{ proxmox_template_host_key }}"
    state: present
  when: set_static_ip | bool
