---

- name: Remove host entry from known_hosts file (1/3)
  delegate_to: localhost
  known_hosts:
    name: "{{ hostvars[item].server_url }}"
    state: absent
  loop: "{{ ansible_play_hosts }}"
  run_once: true

- name: Remove host entry from known_hosts file (2/3)
  delegate_to: localhost
  known_hosts:
    name: '{{ server_ipv4 }}'
    state: absent

- name: Remove host entry from known_hosts file if static IP is being used (3/3)
  delegate_to: localhost
  known_hosts:
    name: '{{ server_ipv4_final }}'
    state: absent
  when: set_static_ip | bool
