---

- name: Create a full clone of the template
  delegate_to: 127.0.0.1
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    name: "{{ server_url }}"
    node: "{{ proxmox_node }}"
    clone: "{{ proxmox_template }}"
    #vcpus: 1
    #cores: "{{ proxmox_kvm_cores }}"
    #memory: "{{ proxmox_kvm_memory }}"
    state: present
    timeout: 300
  register: new_server_info

- debug:
    msg: "{{ new_server_info }}"

- debug:
    msg: "{{ new_server_info.vmid }}"

- name: Start the new VM
  delegate_to: 127.0.0.1
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    vmid: "{{ new_server_info.vmid }}"
    node: "{{ proxmox_node }}"
    #vcpus: 1
    #cores: "{{ proxmox_kvm_cores }}"
    #memory: "{{ proxmox_kvm_memory }}"
    state: started
  register: new_server_info_2

- debug:
    msg: "new_server_info_2: {{ new_server_info_2 }}"

- name: Pause for 20 seconds to let QEMU quest agents startup
  ansible.builtin.pause:
    seconds: 20

- name: Probe proxmox host for VMs network details
  delegate_to: "{{ proxmox_node }}"
  command: |
      sudo qm guest cmd {{ new_server_info.vmid }} network-get-interfaces
  register: qemu_network_info
  ignore_errors: true

- debug:
    msg: "qemu_network_info: {{ qemu_network_info }}"

- debug:
    msg: "IPv4 Address: {{ qemu_network_info.stdout | from_json | json_query('[*][\"ip-addresses\"][0][0] | [1]') | json_query('[\"ip-address\"][0]') }}"
  ignore_errors: true

- debug:
    msg: "IPv6 Address: {{ qemu_network_info.stdout | from_json | json_query('[*][\"ip-addresses\"][0][1] | [1]') | json_query('[\"ip-address\"][0]') }}"
  ignore_errors: true

- name: Assign server IPv4 to a variable
  delegate_to: 127.0.0.1
  set_fact:
    server_ipv4: "{{ qemu_network_info.stdout | from_json | json_query('[*][\"ip-addresses\"][0][0] | [1]') | json_query('[\"ip-address\"][0]') }}"

- name: Assign server IPv6 to a variable
  delegate_to: 127.0.0.1
  set_fact:
    server_ipv6: "{{ qemu_network_info.stdout | from_json | json_query('[*][\"ip-addresses\"][0][1] | [1]') | json_query('[\"ip-address\"][0]') }}"