
# Perform initial server setup
- import_tasks: "{{ role_path }}/tasks/setup_server.yml"
  tags: always

# Perform firewall setup
- import_tasks: "{{ role_path }}/tasks/setup_firewall.yml"
  when: matrix_service | bool
