---

# Set static IP on host if requested
- import_tasks: "{{ role_path }}/tasks/static_ip.yml"
  tags: always

# Perform initial server setup
- import_tasks: "{{ role_path }}/tasks/setup_server.yml"
  tags: always

# Perform firewall setup
#- import_tasks: "{{ role_path }}/tasks/setup_firewall.yml"
#  when: matrix_service | bool
